### ISSUE TITLE
Tachyon Beam Cannon fails to convert

### ISSUE THREAD

**Issue by defensem3ch** [astankiewicz68k/lsdsng-exports#9]
It looks like there's an issue with Tachyon Beam Cannon having invalid instrument data (perhaps instruments used in the wrong channel?). The line of code that errors for me is `if (data.instruments.params[currInstrument][5]&32)` where it says that `data.instruments.params[currInstrument]` is undefined. I've attached the .lsdsng for debugging. Thanks!!
[Tachyon_Beam_Cannon_(IDM_-_Breakcore_-_Speedcore_-_Flashcore_-_20th_Century_(1).zip](https://github.com/AdamGetsAwesome/lsdsng-exports/files/6332755/Tachyon_Beam_Cannon_.IDM_-_Breakcore_-_Speedcore_-_Flashcore_-_20th_Century_.1.zip)

**Comment by defensem3ch** [comment]
Also - if it helps, it seems like the issue is in the wave and/or noise channels

**Comment by AdamGetsAwesome** [comment]
Looks like it was an issue with the speech engine being the 65th instrument. Failed while trying to get the params but since the speech synth doesn't have any, it just crapped out.

Fixed in 95dd6a0
